source "https://rubygems.org"

ruby '3.3.4'

gem "dotenv", "~> 3.1"
gem "encrypted_cookie", "~> 0.0.4"
gem 'json'
gem "sinatra", "~> 4.0"
gem 'sinatra-contrib'
gem 'stripe'
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"